version: "3"
services:
  web:
    image: nginx:latest
    container_name: web
    depends_on:
      - ccrsystem
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $HOME/etc/nginx/conf.d:/etc/nginx/conf.d
      - $HOME/opt:/etc/ssl/certs
    links:
      - ccrsystem
    logging:
      driver: "json-file"
      options:
        max-size: "1000k"
        max-file: "20"
    networks:
      - mysql_app

  todolist:
    image: ccrsystem:latest
    container_name: ccrsystem
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "1000k"
        max-file: "20" 
    external_links:
      - dbmaster
      - dbslave
    networks:
      - mysql_app
networks:
  mysql_app:
    external: true